const products = [
  {
    id: 1,
    name: "Mission 75",
    description:
      "Dedicated, durable and designed for ice cragging, mixed ascents and cold-weather expeditions, the Black Diamond Mission pack is our toughest alpine pack. Featuring an updated BD X-rip 420d fabric with UTS™ coating, these packs are now ultra-durable to withstand season after season of mountain abuse. These packs also provide a balanced carry thanks to its SwingArm shoulder straps, and fully strippable waistbelt, lid and frame-sheet. The new custom metal dogbone ice tool attachment provides secure attachment for technical ice tools and mountaineering axes while a front crampon pouch and a tuck-away rope strap secure gear to the outside. Finally, a drawcord skirt provides a second defense against spindrift and light precip.",

    price: "31,155.00",
    currency: "Rs",
    category: "Bagpacks",
    brand: "Black Diamond",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 2,
    name: "Mission 55",
    description:
      "Dedicated, durable and designed for ice cragging, mixed ascents and cold-weather expeditions, the Black Diamond Mission pack is our toughest alpine pack. Featuring an updated BD X-rip 420d fabric with UTS™ coating, these packs are now ultra-durable to withstand season after season of mountain abuse. These packs also provide a balanced carry thanks to its SwingArm shoulder straps, and fully strippable waistbelt, lid and frame-sheet. The new custom metal dogbone ice tool attachment provides secure attachment for technical ice tools and mountaineering axes while a front crampon pouch and a tuck-away rope strap secure gear to the outside. Finally, a drawcord skirt provides a second defense against spindrift and light precip.",
    price: "29,400.00",
    currency: "USD",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
  {
    id: 123,
    name: "Example Product",
    description: "This is a sample product description.",
    price: "29.99",
    currency: "Rs",
    category: "Electronics",
    brand: "Example Brand",
    imageUrl: "",
    color: "Red",
    size: "Medium",
    stock: 100,
    rating: 4.5,
    reviews: [
      {
        id: 1,
        user: "User123",
        rating: 5,
        comment: "Great product!",
      },
      {
        id: 2,
        user: "User456",
        rating: 4,
        comment: "Good quality.",
      },
    ],
  },
];
